-- Migration 016: AI Grading & Question Generation
-- Adds support for AI-powered grading and intelligent question generation
-- Created: August 12, 2026

-- ============================================================================
-- 1. QUIZ_QUESTIONS EXTENSIONS — AI Generation Support
-- ============================================================================

-- Add AI generation fields to quiz_questions
ALTER TABLE quiz_questions
  ADD COLUMN IF NOT EXISTS ai_generated BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS generated_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS generation_prompt TEXT,
  ADD COLUMN IF NOT EXISTS difficulty VARCHAR(50) DEFAULT 'intermediate'
    CHECK (difficulty IN ('easy', 'intermediate', 'hard')),
  ADD COLUMN IF NOT EXISTS model_answer TEXT,
  ADD COLUMN IF NOT EXISTS rubric TEXT,
  ADD COLUMN IF NOT EXISTS code_language VARCHAR(50),
  ADD COLUMN IF NOT EXISTS starter_code TEXT,
  ADD COLUMN IF NOT EXISTS model_solution TEXT,
  ADD COLUMN IF NOT EXISTS question_type VARCHAR(50)
    CHECK (question_type IN ('multiple', 'short_answer', 'essay', 'code'));

CREATE INDEX IF NOT EXISTS idx_quiz_questions_ai_generated ON quiz_questions(ai_generated);
CREATE INDEX IF NOT EXISTS idx_quiz_questions_generated_at ON quiz_questions(generated_at DESC);
CREATE INDEX IF NOT EXISTS idx_quiz_questions_difficulty ON quiz_questions(difficulty);

-- ============================================================================
-- 2. QUIZ_ANSWERS EXTENSIONS — AI Grading Fields (if not already present)
-- ============================================================================

-- These columns were added in migration 002, but verify they exist
-- Add them with IF NOT EXISTS for safety

ALTER TABLE quiz_answers
  ADD COLUMN IF NOT EXISTS grading_status VARCHAR(50) DEFAULT 'ungraded'
    CHECK (grading_status IN ('ungraded', 'ai_graded', 'instructor_reviewed', 'instructor_overridden')),
  ADD COLUMN IF NOT EXISTS ai_score NUMERIC,
  ADD COLUMN IF NOT EXISTS ai_feedback TEXT,
  ADD COLUMN IF NOT EXISTS ai_graded_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS instructor_score NUMERIC,
  ADD COLUMN IF NOT EXISTS instructor_feedback TEXT,
  ADD COLUMN IF NOT EXISTS is_instructor_graded BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS graded_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMPTZ;

-- Create generated column if it doesn't exist
-- Note: This may fail if the column already exists, which is fine
DO $$
BEGIN
  BEGIN
    ALTER TABLE quiz_answers
      ADD COLUMN effective_score NUMERIC GENERATED ALWAYS AS (
        COALESCE(instructor_score, ai_score, points_earned)
      ) STORED;
  EXCEPTION WHEN duplicate_column THEN
    -- Column already exists, continue
    NULL;
  END;
END $$;

-- Add indexes for AI grading workflow
CREATE INDEX IF NOT EXISTS idx_quiz_answers_ai_score ON quiz_answers(ai_score);
CREATE INDEX IF NOT EXISTS idx_quiz_answers_ai_graded_at ON quiz_answers(ai_graded_at DESC);
CREATE INDEX IF NOT EXISTS idx_quiz_answers_grading_status ON quiz_answers(grading_status);

-- ============================================================================
-- 3. RATE LIMITING TABLE — Prevent Abuse
-- ============================================================================

CREATE TABLE IF NOT EXISTS api_rate_limits (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  endpoint VARCHAR(255) NOT NULL,
  request_count INTEGER DEFAULT 1,
  window_start TIMESTAMPTZ DEFAULT NOW(),
  window_end TIMESTAMPTZ DEFAULT NOW() + INTERVAL '1 minute',
  created_at TIMESTAMPTZ DEFAULT NOW(),

  UNIQUE(user_id, endpoint, window_start)
);

CREATE INDEX IF NOT EXISTS idx_rate_limits_user_endpoint ON api_rate_limits(user_id, endpoint);
CREATE INDEX IF NOT EXISTS idx_rate_limits_window_end ON api_rate_limits(window_end);

-- ============================================================================
-- 4. COMMENTS — Documentation
-- ============================================================================

COMMENT ON COLUMN quiz_questions.ai_generated IS 'True if this question was generated by Claude AI';
COMMENT ON COLUMN quiz_questions.generated_at IS 'Timestamp when this question was AI-generated';
COMMENT ON COLUMN quiz_questions.generation_prompt IS 'The prompt used to generate this question (for audit trail)';
COMMENT ON COLUMN quiz_questions.difficulty IS 'Question difficulty level: easy, intermediate, or hard';
COMMENT ON COLUMN quiz_questions.model_answer IS 'Expected/model answer for short answer questions';
COMMENT ON COLUMN quiz_questions.rubric IS 'Rubric criteria for essay questions';
COMMENT ON COLUMN quiz_questions.code_language IS 'Programming language for code challenges';
COMMENT ON COLUMN quiz_questions.starter_code IS 'Starting code template for code challenges';
COMMENT ON COLUMN quiz_questions.model_solution IS 'Reference solution for code challenges';
COMMENT ON COLUMN quiz_questions.question_type IS 'Type of question: multiple, short_answer, essay, code';

COMMENT ON COLUMN quiz_answers.grading_status IS 'Status: ungraded, ai_graded, instructor_reviewed, instructor_overridden';
COMMENT ON COLUMN quiz_answers.ai_score IS 'Score assigned by Claude AI';
COMMENT ON COLUMN quiz_answers.ai_feedback IS 'Feedback generated by Claude AI';
COMMENT ON COLUMN quiz_answers.ai_graded_at IS 'Timestamp when AI grading occurred';
COMMENT ON COLUMN quiz_answers.effective_score IS 'Final score used: instructor > AI > points_earned (auto-calculated)';

COMMENT ON TABLE api_rate_limits IS 'Tracks API request rates to prevent abuse of expensive operations like question generation';
