/**
 * Quiz Service
 * Shared business logic for quiz CRUD operations
 */

import { getSupabaseClient } from '@/lib/server/supabase-client';
import { createLogger } from '@/lib/logger';
import crypto from 'crypto';

const log = createLogger('QuizService');

export interface QuizCreateInput {
  title: string;
  description?: string;
  time_limit_minutes?: number;
  attempt_limit?: number;
  pass_threshold?: number;
  questions: QuestionInput[];
}

export interface QuestionInput {
  question: string;
  option_a?: string;
  option_b?: string;
  option_c?: string;
  option_d?: string;
  option_e?: string;
  correct_answer: string;
  explanation?: string;
  points?: number;
}

export interface QuizData {
  id: string;
  title: string;
  description?: string;
  instructor_id: string;
  quiz_code: number; // Changed to number for 8-digit numeric code
  total_questions: number;
  total_points: number;
  time_limit_minutes: number;
  attempt_limit: number;
  pass_threshold: number;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

/**
 * Generate a unique 8-digit numeric quiz code
 * Range: 10000000 to 99999999
 * Called by database function - returns value from DB trigger
 */
export function generateQuizCode(): number {
  // Generate random 8-digit number (10000000 to 99999999)
  // The actual unique code is generated by the database function
  return 10000000 + Math.floor(Math.random() * 90000000);
}

/**
 * Create a new quiz with questions
 */
export async function createQuiz(
  instructorEmail: string,
  input: QuizCreateInput
): Promise<{ quiz: QuizData; questionCount: number } | null> {
  try {
    const supabase = getSupabaseClient();
    const quizCode = generateQuizCode();

    // Calculate total points
    const totalPoints = input.questions.reduce((sum, q) => sum + (q.points || 10), 0);

    // Insert quiz
    const { data: quiz, error: quizError } = await supabase
      .from('quizzes')
      .insert({
        title: input.title,
        description: input.description,
        instructor_id: instructorEmail,
        quiz_code: quizCode,
        total_questions: input.questions.length,
        total_points: totalPoints,
        time_limit_minutes: input.time_limit_minutes || 60,
        attempt_limit: input.attempt_limit || 1,
        pass_threshold: input.pass_threshold || 70,
        is_active: true,
      })
      .select()
      .single();

    if (quizError) {
      log.error('Error creating quiz:', quizError);
      return null;
    }

    // Insert questions
    const questionsToInsert = input.questions.map((q, index) => ({
      quiz_id: quiz.id,
      question_number: index + 1,
      question: q.question,
      option_a: q.option_a,
      option_b: q.option_b,
      option_c: q.option_c,
      option_d: q.option_d,
      option_e: q.option_e,
      correct_answer: q.correct_answer.toUpperCase(),
      explanation: q.explanation,
      points: q.points || 10,
    }));

    const { error: questionsError } = await supabase
      .from('quiz_questions')
      .insert(questionsToInsert);

    if (questionsError) {
      log.error('Error inserting questions:', questionsError);
      // Rollback quiz creation
      await supabase.from('quizzes').delete().eq('id', quiz.id);
      return null;
    }

    log.info(`✅ Quiz created: ${quiz.id} (${input.questions.length} questions)`);

    return {
      quiz: quiz as QuizData,
      questionCount: input.questions.length,
    };
  } catch (error) {
    log.error('Error in createQuiz:', error);
    return null;
  }
}

/**
 * Get quiz by ID with questions
 */
export async function getQuizWithQuestions(quizId: string) {
  try {
    const supabase = getSupabaseClient();

    const { data: quiz, error: quizError } = await supabase
      .from('quizzes')
      .select('*')
      .eq('id', quizId)
      .eq('is_active', true)
      .single();

    if (quizError || !quiz) {
      log.warn(`Quiz not found: ${quizId}`);
      return null;
    }

    const { data: questions, error: questionsError } = await supabase
      .from('quiz_questions')
      .select('*')
      .eq('quiz_id', quizId)
      .order('question_number', { ascending: true });

    if (questionsError) {
      log.error('Error fetching questions:', questionsError);
      return null;
    }

    return {
      quiz,
      questions: questions || [],
    };
  } catch (error) {
    log.error('Error in getQuizWithQuestions:', error);
    return null;
  }
}

/**
 * Get quiz by ID without answers (for students)
 */
export async function getQuizForStudent(quizId: string) {
  try {
    const supabase = getSupabaseClient();

    const { data: quiz, error: quizError } = await supabase
      .from('quizzes')
      .select('id, title, description, total_questions, total_points, time_limit_minutes, pass_threshold')
      .eq('id', quizId)
      .eq('is_active', true)
      .single();

    if (quizError || !quiz) {
      log.warn(`Quiz not found: ${quizId}`);
      return null;
    }

    const { data: questions, error: questionsError } = await supabase
      .from('quiz_questions')
      .select('id, question_number, question, option_a, option_b, option_c, option_d, option_e, points')
      .eq('quiz_id', quizId)
      .order('question_number', { ascending: true });

    if (questionsError) {
      log.error('Error fetching questions:', questionsError);
      return null;
    }

    return {
      quiz,
      questions: questions || [],
    };
  } catch (error) {
    log.error('Error in getQuizForStudent:', error);
    return null;
  }
}

/**
 * Update quiz
 */
export async function updateQuiz(
  quizId: string,
  instructorEmail: string,
  updates: {
    title?: string;
    description?: string;
    time_limit_minutes?: number;
    attempt_limit?: number;
    pass_threshold?: number;
  }
) {
  try {
    const supabase = getSupabaseClient();

    // Verify ownership
    const { data: quiz, error: checkError } = await supabase
      .from('quizzes')
      .select('id, instructor_id')
      .eq('id', quizId)
      .single();

    if (checkError || !quiz || quiz.instructor_id !== instructorEmail) {
      log.warn(`Unauthorized update attempt for quiz ${quizId}`);
      return null;
    }

    // Update quiz
    const { data: updated, error: updateError } = await supabase
      .from('quizzes')
      .update({
        ...updates,
        updated_at: new Date().toISOString(),
      })
      .eq('id', quizId)
      .select()
      .single();

    if (updateError) {
      log.error('Error updating quiz:', updateError);
      return null;
    }

    log.info(`✅ Quiz updated: ${quizId}`);
    return updated;
  } catch (error) {
    log.error('Error in updateQuiz:', error);
    return null;
  }
}

/**
 * List instructor's quizzes
 */
export async function listInstructorQuizzes(
  instructorEmail: string,
  options: {
    page?: number;
    limit?: number;
    search?: string;
    status?: 'active' | 'archived' | 'deleted';
  } = {}
) {
  try {
    const supabase = getSupabaseClient();
    const page = options.page || 1;
    const limit = Math.min(options.limit || 20, 100);
    const offset = (page - 1) * limit;

    let query = supabase
      .from('quizzes')
      .select('id, title, description, total_questions, total_points, created_at, updated_at', {
        count: 'exact',
      })
      .eq('instructor_id', instructorEmail)
      .order('created_at', { ascending: false })
      .range(offset, offset + limit - 1);

    // Apply filters
    if (options.search) {
      query = query.ilike('title', `%${options.search}%`);
    }

    if (options.status === 'active') {
      query = query.eq('is_active', true).is('deleted_at', null);
    } else if (options.status === 'archived') {
      query = query.eq('is_active', false);
    } else if (options.status === 'deleted') {
      query = query.not('deleted_at', 'is', null);
    }

    const { data: quizzes, error, count } = await query;

    if (error) {
      log.error('Error listing quizzes:', error);
      return null;
    }

    return {
      quizzes: quizzes || [],
      total: count || 0,
      page,
      limit,
      pages: Math.ceil((count || 0) / limit),
    };
  } catch (error) {
    log.error('Error in listInstructorQuizzes:', error);
    return null;
  }
}

/**
 * Soft delete quiz
 */
export async function softDeleteQuiz(quizId: string, instructorEmail: string) {
  try {
    const supabase = getSupabaseClient();

    // Verify ownership
    const { data: quiz, error: checkError } = await supabase
      .from('quizzes')
      .select('id, instructor_id')
      .eq('id', quizId)
      .single();

    if (checkError || !quiz || quiz.instructor_id !== instructorEmail) {
      log.warn(`Unauthorized delete attempt for quiz ${quizId}`);
      return null;
    }

    // Mark as deleted
    const { data: updated, error: deleteError } = await supabase
      .from('quizzes')
      .update({
        deleted_at: new Date().toISOString(),
        is_active: false,
      })
      .eq('id', quizId)
      .select()
      .single();

    if (deleteError) {
      log.error('Error deleting quiz:', deleteError);
      return null;
    }

    log.info(`✅ Quiz soft-deleted: ${quizId}`);
    return updated;
  } catch (error) {
    log.error('Error in softDeleteQuiz:', error);
    return null;
  }
}
